### ISSUE TITLE
Create first tebako.org site!

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tamatebako.github.io#1]
With description on how to use it.

**Comment by ronaldtse** [comment]
@kwkwan can you please help create the associated site and infrastructure for www.tebako.org? Please follow the example of relaton.org (or whatever the latest incarnation of our sites is). Thanks!

**Comment by ronaldtse** [comment]
Actually, we want to host the site on GitHub Pages, so we don't really need infrastructure.

**Comment by kwkwan** [comment]
The site is available to visit at https://tamatebako.github.io/tebako.org/.  If we want to configure a custom domain, we need to setup related DNS records.

Closed by 81c9c39
