### ISSUE TITLE
Issue blog post

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tamatebako.github.io#2]
Dwarfs uses thrift which is essentially a compiler. So build script  (1) builds thrift, then (2) uses it to create filesytem metadata definitions, then (3) builds a library that processes metadata definition reusing some of the object files created at step (1). In the case of arm64 build on x86_64 steps (1) and (2) need to be x86 while step (3) needs to be arm64.

Similar ruby build script (1) builds miniruby (2) uses miniruby to generate some extra files (3) builds full ruby using some of the object files created at step (1).

In the case of arm64 build on x86_64 steps (1) and (2) need to be x86 while step (3) needs to be arm64.

It is possible th create build scripts both for dwarfs and for ruby as described above.  For dwarfs complexity is low, for Ruby complexity is high.  Howeevr we need to accept the fact that our build scripts will diverge from baselines in both cases.

**Comment by maxirmx** [comment]
Let it be a blog post regarding Ruby 3.3 support
