### ISSUE TITLE
In the readme and the tebako blog post provide instructions on how to migrate from Ocra to aibika

### ISSUE THREAD

**Issue by maxirmx** [tamatebako/tamatebako.github.io#24]
@maxirmx thanks! In the readme and the tebako blog post can you provide instructions on how to migrate from Ocra to aibika?

_Originally posted by @ronaldtse in https://github.com/tamatebako/aibika/issues/9#issuecomment-1692477040_

**Comment by maxirmx** [comment]
Aibika readme updated

**Comment by ronaldtse** [comment]
Thanks @maxirmx ! Can you write a blog post on how to migrate from Ocra to Aibika, using a simple example? Thanks.

**Comment by maxirmx** [comment]
@ronaldtse 
I plan to publush aibika gem, do packed_mn migration to aibika and ruby 2.7 --> ruby 3.1 for Windows   (tebako is ruby 3.1 already) and then create the blog post
That will add some background and value to the blog post I guess

**Comment by ronaldtse** [comment]
This is exactly how I wish it could be done. Excellent plan -- thanks!
