### ISSUE TITLE
Blog post about rationale behind legacy executable packagers and approaches

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tamatebako.github.io#4]
A post about rationale behind executable packagers and approaches taken by legacy solutions (ruby-packer, ocra).

**Comment by maxirmx** [comment]
@ronaldtse  @CAMOBAP 
Please have a look. I am seeking for reviews and better ideas
[post-1.docx](https://github.com/tamatebako/tebako.org/files/10418782/post-1.docx)
[post-1.pdf](https://github.com/tamatebako/tebako.org/files/10418783/post-1.pdf)

**Comment by CAMOBAP** [comment]
@maxirmx thanks for preparing great report

Few questions from my side:

> You not only have to build separate packages for each OS, but also each OS version

Am I right that this related to dynamic linking with "system" libs like glib?
Or you mean some other sort of problems?

**Comment by maxirmx** [comment]
> Few questions from my side:
> 
> > You not only have to build separate packages for each OS, but also each OS version
> 
> Am I right that this related to dynamic linking with "system" libs like glib? Or you mean some other sort of problems?

Thank you, @CAMOBAP, it is a good question
I think it was not a good statement.  I thought about environment like debian where you need to provide a separate package for each major version

**Comment by maxirmx** [comment]
[post-1.docx](https://github.com/tamatebako/tebako.org/files/10429121/post-1.docx)
[post-1.pdf](https://github.com/tamatebako/tebako.org/files/10429122/post-1.pdf)

Updated

**Comment by CAMOBAP** [comment]
> > Few questions from my side:
> > > You not only have to build separate packages for each OS, but also each OS version
> > 
> > 
> > Am I right that this related to dynamic linking with "system" libs like glib? Or you mean some other sort of problems?
> 
> Thank you, @CAMOBAP, it is a good question I think was not a reasonable statement.

Thanks for update, sorry but it's still not clear why exactly: "... you have to treat each distribution as another OS, further increasing the number of combinations" 

I hope snap/flatpak/appimage should help us minimize such issues. The only problem which I remember sofar is glib link to specific version (runtime linker error)
