### ISSUE TITLE
Blog post about technology used in tebako and tebako dataflow

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tamatebako.github.io#5]

**Comment by maxirmx** [comment]
[post-2.docx](https://github.com/tamatebako/tebako.org/files/10831180/post-2.docx)
[post-2.pdf](https://github.com/tamatebako/tebako.org/files/10831181/post-2.pdf)

@ronaldtse @CAMOBAP  Please review when you a have a chance. Thank you.

**Comment by CAMOBAP** [comment]
LGTM. Will we deploy it somewhere on metanorma.org or tebako.org?

**Comment by maxirmx** [comment]
I believe there was a plan to create tebako.org site.

**Comment by ronaldtse** [comment]
Deployed. Thanks guys!
